/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 jedi.glb --types --bones --shadows --transform 
Files: jedi.glb [7.57MB] > /public/assets/jedi-transformed.glb [1.81MB] (76%)
*/

import * as THREE from "three";
import { useEffect, useMemo, useRef } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations, Cylinder } from "@react-three/drei";
import { GLTF, SkeletonUtils } from "three-stdlib";
import { useControls } from "leva";
import { AdditiveBlending, AnimationAction, Group } from "three";

type ActionName = "attack" | "standing" | "withdraw";

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}

type GLTFResult = GLTF & {
  nodes: {
    LeftUpLeg: object;
    LeftLeg: object;
    LeftFoot: object;
    LeftToeBase: object;
    RightUpLeg: object;
    RightLeg: object;
    RightFoot: object;
    RightToeBase: object;
    Spine: object;
    Spine1: object;
    Spine2: object;
    Neck: object;
    Head: object;
    LeftShoulder: object;
    LeftArm: object;
    LeftForeArm: object;
    LeftHand: object;
    LeftHandIndex1: object;
    LeftHandIndex2: object;
    LeftHandIndex3: object;
    LeftHandMiddle1: object;
    LeftHandMiddle2: object;
    LeftHandMiddle3: object;
    LeftHandPinky1: object;
    LeftHandPinky2: object;
    LeftHandPinky3: object;
    LeftHandRing1: object;
    LeftHandRing2: object;
    LeftHandRing3: object;
    LeftHandThumb1: object;
    LeftHandThumb2: object;
    LeftHandThumb3: object;
    RightShoulder: object;
    RightArm: object;
    RightForeArm: object;
    RightHand: object;
    RightHandIndex1: object;
    RightHandIndex2: object;
    RightHandIndex3: object;
    RightHandMiddle1: object;
    RightHandMiddle2: object;
    RightHandMiddle3: object;
    RightHandPinky1: object;
    RightHandPinky2: object;
    RightHandPinky3: object;
    RightHandRing1: object;
    RightHandRing2: object;
    RightHandRing3: object;
    RightHandThumb1: object;
    RightHandThumb2: object;
    RightHandThumb3: object;
    avaturn_body: THREE.SkinnedMesh;
    avaturn_glasses_0: THREE.SkinnedMesh;
    avaturn_glasses_1: THREE.SkinnedMesh;
    avaturn_hair_0: THREE.SkinnedMesh;
    avaturn_hair_1: THREE.SkinnedMesh;
    avaturn_look_0: THREE.SkinnedMesh;
    Hips: THREE.Bone;
  };
  materials: {
    avaturn_body_material: THREE.MeshStandardMaterial;
    avaturn_glasses_0_material: THREE.MeshStandardMaterial;
    avaturn_glasses_1_material: THREE.MeshStandardMaterial;
    avaturn_hair_0_material: THREE.MeshStandardMaterial;
    avaturn_hair_1_material: THREE.MeshStandardMaterial;
    avaturn_look_0_material: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Jedi(props: JSX.IntrinsicElements["group"]) {
  const {
    roughness,
    metalness,
    emissive,
    emissiveIntensity,
    opacity,
    lightIntensity,
    lightDistance,
    lightColor,
  } = useControls("Jedi", {
    roughness: { value: 0.5, min: 0, max: 1, step: 0.01 },
    metalness: { value: 0.5, min: 0, max: 1, step: 0.01 },
    emissive: { value: "#ff00ff" },
    emissiveIntensity: { value: 10, min: 0, max: 10, step: 0.1 },
    opacity: { value: 0.7, min: 0, max: 1, step: 0.01 },
    lightIntensity: { value: 1.5, min: 0, max: 10, step: 0.1 },
    lightDistance: { value: 5, min: 0, max: 20, step: 0.1 },
    lightColor: { value: "#790079" },
  });

  const group = useRef<Group>(null);
  const isActionPlaying = useRef(false);
  const activeAction = useRef<AnimationAction | null>(null);

  const { scene, animations } = useGLTF(
    "/assets/jedi-transformed.glb"
  ) as GLTFResult;

  const { scene: lightsaber } = useGLTF("/assets/lightsaber.glb");

  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone) as GLTFResult;
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    const standing = actions.standing;
    if (standing) {
      standing.play();
      activeAction.current = standing;
    }
  }, [actions]);

  useEffect(() => {
    lightsaber.visible = false;
  }, []);

  // TODO: Clean up this function
  const handleClick = async () => {
    if (isActionPlaying.current || !activeAction.current) {
      return;
    }

    const standing = actions.standing;
    const withdraw = actions.withdraw;
    const attack = actions.attack;

    if (!standing || !withdraw || !attack) {
      return;
    }

    isActionPlaying.current = true;

    try {
      withdraw.reset().play();
      activeAction.current.crossFadeTo(withdraw, 0.2, false);
      activeAction.current = withdraw;

      const { duration: withdrawDuration } = withdraw.getClip();

      setTimeout(() => {}, (withdrawDuration / 2) * 1000);

      setTimeout(() => {
        lightsaber.visible = true;
      }, (withdrawDuration / 2) * 1000);

      await new Promise((resolve) =>
        setTimeout(resolve, withdrawDuration * 900)
      );

      // Cross-fade to "attack"
      attack.reset().play();
      activeAction.current.crossFadeTo(attack, 0.1, false);
      activeAction.current = attack;

      await new Promise((resolve) =>
        setTimeout(resolve, attack.getClip().duration * 1000)
      );

      // Cross-fade back to "standing"
      standing.reset().play();
      activeAction.current.crossFadeTo(standing, 0.01, false);
      activeAction.current = standing;
    } catch (error) {
      console.error("Error during animation:", error);
    } finally {
      isActionPlaying.current = false;
    }
  };

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      onClick={handleClick}
      position={[0, -0.8, 0]}
    >
      <group name="Scene">
        <group name="Avatar">
          <primitive
            object={nodes.Hips}
            name="Hips"
            position={[0, 0.967, 0.014]}
            rotation={[-0.008, 0, 0]}
          >
            <primitive
              object={nodes.LeftUpLeg}
              name="LeftUpLeg"
              position={[0.086, -0.03, 0.001]}
              rotation={[-0.005, 0, -Math.PI]}
            >
              <primitive
                object={nodes.LeftLeg}
                name="LeftLeg"
                position={[0, 0.415, 0]}
                rotation={[-0.088, -0.001, 0]}
              >
                <primitive
                  object={nodes.LeftFoot}
                  name="LeftFoot"
                  position={[0, 0.431, 0]}
                  rotation={[1.149, 0.027, -0.001]}
                >
                  <primitive
                    object={nodes.LeftToeBase}
                    name="LeftToeBase"
                    position={[0, 0.16, 0]}
                    rotation={[0.527, -0.009, 0.013]}
                  />
                </primitive>
              </primitive>
            </primitive>
            <primitive
              object={nodes.RightUpLeg}
              name="RightUpLeg"
              position={[-0.086, -0.03, 0.001]}
              rotation={[-0.005, 0, Math.PI]}
            >
              <primitive
                object={nodes.RightLeg}
                name="RightLeg"
                position={[0, 0.415, 0]}
                rotation={[-0.088, 0.034, 0]}
              >
                <primitive
                  object={nodes.RightFoot}
                  name="RightFoot"
                  position={[0, 0.431, 0]}
                  rotation={[1.15, -0.035, 0.032]}
                >
                  <primitive
                    object={nodes.RightToeBase}
                    name="RightToeBase"
                    position={[0, 0.16, 0]}
                    rotation={[0.526, 0.001, -0.008]}
                  />
                </primitive>
              </primitive>
            </primitive>
            <primitive
              object={nodes.Spine}
              name="Spine"
              position={[0, 0.096, 0]}
              rotation={[0.019, 0, 0]}
            >
              <primitive
                object={nodes.Spine1}
                name="Spine1"
                position={[0, 0.119, 0]}
                rotation={[-0.122, 0, 0]}
              >
                <primitive
                  object={nodes.Spine2}
                  name="Spine2"
                  position={[0, 0.162, 0]}
                  rotation={[-0.15, 0, 0]}
                >
                  <primitive
                    object={nodes.Neck}
                    name="Neck"
                    position={[0, 0.188, 0]}
                    rotation={[0.487, 0, 0]}
                  >
                    <primitive
                      object={nodes.Head}
                      name="Head"
                      position={[0, 0.12, 0]}
                      rotation={[-0.226, 0, 0]}
                    />
                  </primitive>
                  <primitive
                    object={nodes.LeftShoulder}
                    name="LeftShoulder"
                    position={[0.052, 0.165, 0.009]}
                    rotation={[1.694, 0, -Math.PI / 2]}
                  >
                    <primitive
                      object={nodes.LeftArm}
                      name="LeftArm"
                      position={[0, 0.15, 0]}
                      rotation={[-0.004, 0.168, -0.056]}
                    >
                      <primitive
                        object={nodes.LeftForeArm}
                        name="LeftForeArm"
                        position={[0, 0.252, 0]}
                        rotation={[0.009, 0, 0.076]}
                      >
                        <primitive
                          object={nodes.LeftHand}
                          name="LeftHand"
                          position={[0, 0.257, 0]}
                          rotation={[0.002, -0.002, -0.021]}
                        >
                          <primitive
                            object={nodes.LeftHandIndex1}
                            name="LeftHandIndex1"
                            position={[-0.021, 0.081, 0.002]}
                            rotation={[0.003, 0.013, 0.119]}
                          >
                            <primitive
                              object={nodes.LeftHandIndex2}
                              name="LeftHandIndex2"
                              position={[0, 0.038, 0]}
                              rotation={[0.027, -0.03, -0.001]}
                            >
                              <primitive
                                object={nodes.LeftHandIndex3}
                                name="LeftHandIndex3"
                                position={[0, 0.021, 0]}
                                rotation={[0.001, -0.001, 0.001]}
                              />
                            </primitive>
                          </primitive>
                          <primitive
                            object={nodes.LeftHandMiddle1}
                            name="LeftHandMiddle1"
                            position={[0, 0.084, 0]}
                            rotation={[0.031, -0.06, 0.026]}
                          >
                            <primitive
                              object={nodes.LeftHandMiddle2}
                              name="LeftHandMiddle2"
                              position={[0, 0.04, 0]}
                              rotation={[-0.012, 0.006, -0.007]}
                            >
                              <primitive
                                object={nodes.LeftHandMiddle3}
                                name="LeftHandMiddle3"
                                position={[0, 0.024, 0]}
                                rotation={[0.017, -0.007, 0.002]}
                              />
                            </primitive>
                          </primitive>
                          <primitive
                            object={nodes.LeftHandPinky1}
                            name="LeftHandPinky1"
                            position={[0.036, 0.074, 0.005]}
                            rotation={[0.027, -0.129, -0.082]}
                          >
                            <primitive
                              object={nodes.LeftHandPinky2}
                              name="LeftHandPinky2"
                              position={[0, 0.027, 0]}
                              rotation={[-0.001, -0.021, -0.001]}
                            >
                              <primitive
                                object={nodes.LeftHandPinky3}
                                name="LeftHandPinky3"
                                position={[0, 0.018, 0]}
                                rotation={[0.004, -0.016, -0.006]}
                              />
                            </primitive>
                          </primitive>
                          <primitive
                            object={nodes.LeftHandRing1}
                            name="LeftHandRing1"
                            position={[0.02, 0.084, 0.001]}
                            rotation={[0.026, -0.095, -0.05]}
                          >
                            <primitive
                              object={nodes.LeftHandRing2}
                              name="LeftHandRing2"
                              position={[0, 0.034, 0]}
                              rotation={[-0.001, 0.018, -0.002]}
                            >
                              <primitive
                                object={nodes.LeftHandRing3}
                                name="LeftHandRing3"
                                position={[0, 0.022, 0]}
                                rotation={[0.001, 0.027, 0]}
                              />
                            </primitive>
                          </primitive>
                          <primitive
                            object={nodes.LeftHandThumb1}
                            name="LeftHandThumb1"
                            position={[-0.021, 0.036, 0.014]}
                            rotation={[0.364, -0.048, 0.828]}
                          >
                            <primitive
                              object={nodes.LeftHandThumb2}
                              name="LeftHandThumb2"
                              position={[0, 0.028, 0]}
                              rotation={[0.078, -0.07, -0.561]}
                            >
                              <primitive
                                object={nodes.LeftHandThumb3}
                                name="LeftHandThumb3"
                                position={[0, 0.026, 0]}
                                rotation={[-0.056, 0.008, 0.033]}
                              />
                            </primitive>
                          </primitive>
                        </primitive>
                      </primitive>
                    </primitive>
                  </primitive>
                  <primitive
                    object={nodes.RightShoulder}
                    name="RightShoulder"
                    position={[-0.052, 0.165, 0.009]}
                    rotation={[1.694, 0, Math.PI / 2]}
                  >
                    <primitive
                      object={nodes.RightArm}
                      name="RightArm"
                      position={[0, 0.15, 0]}
                      rotation={[-0.004, -0.168, 0.056]}
                    >
                      <primitive
                        object={nodes.RightForeArm}
                        name="RightForeArm"
                        position={[0, 0.252, 0]}
                        rotation={[0.009, 0, -0.076]}
                      >
                        <primitive
                          object={nodes.RightHand}
                          name="RightHand"
                          position={[0, 0.257, 0]}
                          rotation={[0.002, 0.002, 0.021]}
                        >
                          <primitive
                            object={lightsaber}
                            position={[-0.1, 0.05, 0.012]}
                            rotation={[0, 0, -1.4]}
                            scale={0.25}
                          >
                            <Cylinder args={[0.04, 0.04, 4]} position-y={3}>
                              <meshPhysicalMaterial
                                emissive={emissive}
                                emissiveIntensity={emissiveIntensity}
                                opacity={opacity}
                                blending={AdditiveBlending}
                              />
                              <pointLight
                                intensity={lightIntensity}
                                distance={lightDistance}
                                color={lightColor}
                              />
                            </Cylinder>
                          </primitive>

                          <primitive
                            object={nodes.RightHandIndex1}
                            name="RightHandIndex1"
                            position={[0.021, 0.081, 0.002]}
                            rotation={[0.003, -0.013, -0.119]}
                          >
                            <primitive
                              object={nodes.RightHandIndex2}
                              name="RightHandIndex2"
                              position={[0, 0.038, 0]}
                              rotation={[0.027, 0.03, 0.001]}
                            >
                              <primitive
                                object={nodes.RightHandIndex3}
                                name="RightHandIndex3"
                                position={[0, 0.021, 0]}
                                rotation={[0.001, 0.001, -0.001]}
                              />
                            </primitive>
                          </primitive>
                          <primitive
                            object={nodes.RightHandMiddle1}
                            name="RightHandMiddle1"
                            position={[0, 0.084, 0]}
                            rotation={[0.031, 0.06, -0.026]}
                          >
                            <primitive
                              object={nodes.RightHandMiddle2}
                              name="RightHandMiddle2"
                              position={[0, 0.04, 0]}
                              rotation={[-0.012, -0.006, 0.007]}
                            >
                              <primitive
                                object={nodes.RightHandMiddle3}
                                name="RightHandMiddle3"
                                position={[0, 0.024, 0]}
                                rotation={[0.017, 0.007, -0.002]}
                              />
                            </primitive>
                          </primitive>
                          <primitive
                            object={nodes.RightHandPinky1}
                            name="RightHandPinky1"
                            position={[-0.036, 0.074, 0.005]}
                            rotation={[0.027, 0.129, 0.082]}
                          >
                            <primitive
                              object={nodes.RightHandPinky2}
                              name="RightHandPinky2"
                              position={[0, 0.027, 0]}
                              rotation={[-0.001, 0.021, 0.001]}
                            >
                              <primitive
                                object={nodes.RightHandPinky3}
                                name="RightHandPinky3"
                                position={[0, 0.018, 0]}
                                rotation={[0.004, 0.016, 0.006]}
                              />
                            </primitive>
                          </primitive>
                          <primitive
                            object={nodes.RightHandRing1}
                            name="RightHandRing1"
                            position={[-0.02, 0.084, 0.001]}
                            rotation={[0.026, 0.095, 0.05]}
                          >
                            <primitive
                              object={nodes.RightHandRing2}
                              name="RightHandRing2"
                              position={[0, 0.034, 0]}
                              rotation={[-0.001, -0.018, 0.002]}
                            >
                              <primitive
                                object={nodes.RightHandRing3}
                                name="RightHandRing3"
                                position={[0, 0.022, 0]}
                                rotation={[0.001, -0.027, 0]}
                              />
                            </primitive>
                          </primitive>
                          <primitive
                            object={nodes.RightHandThumb1}
                            name="RightHandThumb1"
                            position={[0.021, 0.036, 0.014]}
                            rotation={[0.364, 0.048, -0.828]}
                          >
                            <primitive
                              object={nodes.RightHandThumb2}
                              name="RightHandThumb2"
                              position={[0, 0.028, 0]}
                              rotation={[0.078, 0.07, 0.561]}
                            >
                              <primitive
                                object={nodes.RightHandThumb3}
                                name="RightHandThumb3"
                                position={[0, 0.026, 0]}
                                rotation={[-0.056, -0.008, -0.033]}
                              />
                            </primitive>
                          </primitive>
                        </primitive>
                      </primitive>
                    </primitive>
                  </primitive>
                </primitive>
              </primitive>
            </primitive>
          </primitive>
          <skinnedMesh
            name="avaturn_body"
            geometry={nodes.avaturn_body.geometry}
            material={materials.avaturn_body_material}
            skeleton={nodes.avaturn_body.skeleton}
            material-roughness={roughness}
            material-metalness={metalness}
          />
          <skinnedMesh
            name="avaturn_glasses_0"
            geometry={nodes.avaturn_glasses_0.geometry}
            material={materials.avaturn_glasses_0_material}
            skeleton={nodes.avaturn_glasses_0.skeleton}
            material-roughness={roughness}
            material-metalness={metalness}
          />
          <skinnedMesh
            name="avaturn_glasses_1"
            geometry={nodes.avaturn_glasses_1.geometry}
            material={materials.avaturn_glasses_1_material}
            skeleton={nodes.avaturn_glasses_1.skeleton}
            material-roughness={roughness}
            material-metalness={metalness}
          />
          <skinnedMesh
            name="avaturn_hair_0"
            geometry={nodes.avaturn_hair_0.geometry}
            material={materials.avaturn_hair_0_material}
            skeleton={nodes.avaturn_hair_0.skeleton}
            material-roughness={roughness}
            material-metalness={metalness}
          />
          <skinnedMesh
            name="avaturn_hair_1"
            geometry={nodes.avaturn_hair_1.geometry}
            material={materials.avaturn_hair_1_material}
            skeleton={nodes.avaturn_hair_1.skeleton}
            material-roughness={roughness}
            material-metalness={metalness}
          />
          <skinnedMesh
            name="avaturn_look_0"
            geometry={nodes.avaturn_look_0.geometry}
            material={materials.avaturn_look_0_material}
            skeleton={nodes.avaturn_look_0.skeleton}
            material-roughness={roughness}
            material-metalness={metalness}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/assets/jedi-transformed.glb");
